# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-10 21:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('content2', models.TextField()),
                ('content3', models.TextField()),
            ],
        ),
    ]
