# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-10 21:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='content2',
        ),
        migrations.RemoveField(
            model_name='posts',
            name='content3',
        ),
    ]
