# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-11 12:00
from __future__ import unicode_literals

from django.db import migrations, models
import posts.models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_posts_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='content',
            field=models.CharField(max_length=200, validators=[posts.models.validate_content]),
        ),
    ]
