# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-30 19:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20181230_2051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, default='test'),
        ),
    ]
